language: node_js
node_js:
- '5.7'
cache:
  directories:
  - node_modules
after_success: npm run coverage
notifications:
  slack:
    secure: cGsqJj0H1tpwY2r6m16lH3OLIUIzkr7VL3yDKmupFtD/uEFvjyMOwB0rpYuMHgSTRWlOuiLtgznHtukk3zAvgZDAVw2c9n3IVzLBjz0QqjPJTuShZMMvGvMOkdpzk/PDAB0xMovxB5covJC/TDQcN7NLa5Err3ps5WbKgj09rmVomiOW+QJkH7xzx6CyHmnQqk4Wqw9IEEQdRMf6fIbo5JZUFa5ZhSzkVpNmjX8fGis2U8fX/zEO9DA+9e8aQYLYsewUfpohAAJo2nPT1iq53VeRRLF3t4B4WwnuuKsWwa7zfnyqcz1vn+v8NeqKO1nK8vVDUoKfIFo0WBXrjbsWBleSXyNxYsOlxcMvMzlQCs9r1dHoOElblqHgGXssUfbaV/3xsyEtai0acN5rI+a0DwKutO/XbjQa0IVFh1FzEaNT/hmE1KN0nLaQl+HN3BHZkLQHg+QXTjPC6l80nP36dxv47gHRZGqfu32Yyzp7m67MJsmx0yMqNUl8bUim3acKCjEpGBLNsWw5SUA52W/kHRDDj5geL6F65St4H7lKFrFqTDukKC/ZtRtvSjlM2FInf00FnlHop1Z/BrvBSmx8MeNroOKaGJ10JGlYKafuJVbKWEYDjN7lDzRVbZJiILaESxJEOjpaJZpm7hq5Nxe5Dzr4w/NoMjSFv/fZE10PLMM=
